apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: light-service-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/voidschema/gitops-observability-stack'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
